/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BodyRouteImport } from './routes/body'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as HistoryIdRouteImport } from './routes/history_.$id'
import { Route as LeaderboardUserIdRouteImport } from './routes/leaderboard_.$userId'
import { Route as WorkoutSlugRouteImport } from './routes/workout.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyRoute = BodyRouteImport.update({
  id: '/body',
  path: '/body',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/history_/$id',
  path: '/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardUserIdRoute = LeaderboardUserIdRouteImport.update({
  id: '/leaderboard_/$userId',
  path: '/leaderboard/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutSlugRoute = WorkoutSlugRouteImport.update({
  id: '/workout/$slug',
  path: '/workout/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/body': typeof BodyRoute
  '/builder': typeof BuilderRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/history/$id': typeof HistoryIdRoute
  '/leaderboard/$userId': typeof LeaderboardUserIdRoute
  '/workout/$slug': typeof WorkoutSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/body': typeof BodyRoute
  '/builder': typeof BuilderRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/history/$id': typeof HistoryIdRoute
  '/leaderboard/$userId': typeof LeaderboardUserIdRoute
  '/workout/$slug': typeof WorkoutSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/body': typeof BodyRoute
  '/builder': typeof BuilderRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/history_/$id': typeof HistoryIdRoute
  '/leaderboard_/$userId': typeof LeaderboardUserIdRoute
  '/workout/$slug': typeof WorkoutSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/body'
    | '/builder'
    | '/history'
    | '/leaderboard'
    | '/plan'
    | '/profile'
    | '/progress'
    | '/history/$id'
    | '/leaderboard/$userId'
    | '/workout/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/body'
    | '/builder'
    | '/history'
    | '/leaderboard'
    | '/plan'
    | '/profile'
    | '/progress'
    | '/history/$id'
    | '/leaderboard/$userId'
    | '/workout/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/body'
    | '/builder'
    | '/history'
    | '/leaderboard'
    | '/plan'
    | '/profile'
    | '/progress'
    | '/history_/$id'
    | '/leaderboard_/$userId'
    | '/workout/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BodyRoute: typeof BodyRoute
  BuilderRoute: typeof BuilderRoute
  HistoryRoute: typeof HistoryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PlanRoute: typeof PlanRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  HistoryIdRoute: typeof HistoryIdRoute
  LeaderboardUserIdRoute: typeof LeaderboardUserIdRoute
  WorkoutSlugRoute: typeof WorkoutSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body': {
      id: '/body'
      path: '/body'
      fullPath: '/body'
      preLoaderRoute: typeof BodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history_/$id': {
      id: '/history_/$id'
      path: '/history/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard_/$userId': {
      id: '/leaderboard_/$userId'
      path: '/leaderboard/$userId'
      fullPath: '/leaderboard/$userId'
      preLoaderRoute: typeof LeaderboardUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/$slug': {
      id: '/workout/$slug'
      path: '/workout/$slug'
      fullPath: '/workout/$slug'
      preLoaderRoute: typeof WorkoutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BodyRoute: BodyRoute,
  BuilderRoute: BuilderRoute,
  HistoryRoute: HistoryRoute,
  LeaderboardRoute: LeaderboardRoute,
  PlanRoute: PlanRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  HistoryIdRoute: HistoryIdRoute,
  LeaderboardUserIdRoute: LeaderboardUserIdRoute,
  WorkoutSlugRoute: WorkoutSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
